# Generated by Django 3.1.1 on 2020-09-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ngoadmin_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoadmin',
            name='pincode',
        ),
    ]
