# Generated by Django 3.1.1 on 2020-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ngoadmin_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoadmin',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
