# Generated by Django 3.1.1 on 2020-09-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200926_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngoadmin',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
