# Generated by Django 3.1.1 on 2020-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200927_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
